name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Build, publish
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build --no-cache -t mvgorshkoff/gateway ./library_system/gateway/
          docker push mvgorshkoff/gateway:latest
          docker build --no-cache -t mvgorshkoff/ratingsystem ./library_system/rating_system/
          docker push mvgorshkoff/ratingsystem:latest
          docker build --no-cache -t mvgorshkoff/librarysystem ./library_system/library_system/
          docker push mvgorshkoff/librarysystem:latest
          docker build --no-cache -t mvgorshkoff/reservationsystem ./library_system/reservation_system/
          docker push mvgorshkoff/reservationsystem:latest

      - name: Deploy to kubernetes
        timeout-minutes: 5
        env:
          SERVER: "${{secrets.OKTETO_SERVER}}"
          TOKEN: "${{secrets.OKTETO_TOKEN}}"
          CERTIFICATE: "${{secrets.K8S_CLUSTER_CERT}}"
        run: |
          kubectl config set-cluster rsoi-cluster --server=$SERVER
          kubectl config set-credentials dev --token=$TOKEN
          kubectl config set clusters.rsoi-cluster.certificate-authority-data $CERTIFICATE
          kubectl config set-context production --cluster=rsoi-cluster --user=dev --namespace=villainnumberone
          kubectl config use-context production
          helm upgrade --install rsoi-lab4 ./kubernetes/library
          kubectl apply -f ./kubernetes/ingress.yaml

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: <variant>/postman/collection.json
          environment: <variant>/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 4
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"